### ISSUE TITLE
Stuck on "generating payload"?

### ISSUE THREAD

**Issue by 7MinSec** [nccgroup/chuckle#4]
Hi,

I just grabbed Chuckle and the latest tool pre-reqs and once I run chuckle.sh, I'm fine until the point of "Generating payload..." and then I'm hung there forever.  Any ideas what might be gumming things up behind the scenes?

Thanks,
Brian

**Comment by craigsblackie** [comment]
Hey, sorry you're having issues. I find that veil-evasion can be little tricky to get installed and working sometimes. Make sure you are able to make a GO reverse HTTPS payload in veil, if this fails it's likely the issue.
Craig

**Comment by 7MinSec** [comment]
Craig,

You're right on.  I had run veil-evasion and thought it installed correctly, but running the command by itself now seems to kick off the install..._again_. Hmm I'll work through this and see if it doesn't solve my chuckle problem, thanks!

B

On Mar 19, 2016, at 11:52 PM, craigsblackie <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey, sorry you're having issues. I find that veil-evasion can be little tricky to get installed and working sometimes. Make sure you are able to make a GO reverse HTTPS payload in veil, if this fails it's likely the issue.
Craig

##

**Comment by craigsblackie** [comment]
I'll close this for the meantime, let me know if you have any more issues.
